#useful reference: http://dan-blanchard.roughdraft.io/7045057-quicker-travis-builds-that-rely-on-numpy-and-scipy-using-miniconda
#useful reference: https://gist.github.com/dan-blanchard/7045057    

language: python
python:
    - "3.4"
before_install:
    #- sudo: false  ...this is supposed to allow travis to run the build on new 'containers'
    - pip install pytest pytest-cov
    - pip install nose
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda/bin:$PATH
   # - conda update --yes conda
    # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
    - sudo rm -rf /dev/shm
    - sudo ln -s /run/shm /dev/shm
    
install:
    - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy matplotlib nose dateutil pandas statsmodels
    # Coverage packages are on my binstar channel
    - which python
    - python --version
    
script:
  - py.test 
  - pwd
  - nosetests --nocapture

# Calculate coverage
#after_success:
#  - coveralls --config_file .coveragerc
    
notifications:
  email: false
 
    

